categories:
  sf-books: ~

settings:
  evoweb.sf_books.bookPageId:
    default: 0
    type: int
    category: sf-books
  evoweb.sf_books.authorPageId:
    default: 0
    type: int
    category: sf-books
  evoweb.sf_books.categoryPageId:
    default: 0
    type: int
    category: sf-books
  evoweb.sf_books.seriesPageId:
    default: 0
    type: int
    category: sf-books
  evoweb.sf_books.searchPageId:
    default: 0
    type: int
    category: sf-books
  evoweb.sf_books.excludeCategories:
    default: ''
    type: string
    category: sf-books
